class Problem2 {

    /*
     * Problem 2
     *
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     */
    static int problem2(int max) {
        int sum = 2;
        int i = 1;
        int j = 2;
        while (i < max && j < max) {
            i = i + 2 * j;
            j = i - j; // j = i + j
            i = i - j; // i = j
            if (j % 2 == 0) sum += j;
        }
        return sum;
    }

}
